const moviesActionTypes = {
    GET_MOVIES : "GET_MOVIES",
    START_FETCHING : "START_FETCHING",
    FETCH_ERROR : "FETCH_ERROR",
    FINISHED_FETCHING : "FINISHED_FETCHING",
    FETCH_MOVIE_DETAILS: "FETCH_MOVIE_DETAILS",
    FETCH_MOVIE_SHOWTIME : "FETCH_MOVIE_SHOWTIME"
};

export default moviesActionTypes